services:
  - type: web
    name: racehub-backend
    env: java
    region: frankfurt
    plan: free
    branch: security/env-variables
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/racehub-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_USERNAME
        sync: false
    healthCheckPath: /actuator/health
    autoDeploy: true